### ISSUE TITLE
Could not find libc

### ISSUE THREAD

**Issue by auxsvr** [kmaork/pyinjector#12]
Using pyinjector 1.0.5 with madbg 1.2.0, I get:
> pyinjector.pyinjector.InjectorError: injector_attach returned -4: Could not find libc

attempting to attach to a Python program. This is on Linux 5.15.8.

**Comment by kmaork** [comment]
What process are to trying to inject to? Could you post here its `/proc/<pid>/maps`?

**Comment by auxsvr** [comment]
It's pylsp, here is the file [maps.txt](https://github.com/kmaork/pyinjector/files/8091812/maps.txt).

**Comment by kmaork** [comment]
Your environment seems a bit unusual - is it possible `/usr/lib64/libc.so.6` is not a symlink on your machine? Please post the output of `ls -l /usr/lib64/libc.so.6`

**Comment by auxsvr** [comment]
> \> ls -l /usr/lib64/libc.so.6 
-rwxr-xr-x 1 root root 2,5M Dec  6 00:00 /usr/lib64/libc.so.6

Indeed, it's not a symlink. It's on openSUSE Tumbleweed.

**Comment by kmaork** [comment]
Fixing this requires a change in kubo/injector - https://github.com/kubo/injector/blob/master/src/linux/elf.c#L257 will need to support `libc.so.6` (and probably `libc.so` too) instead of just `libc-2.xx.so`. I see this issue has surfaced in kubo/injector as well - https://github.com/kubo/injector/issues/15.
Until it is resolved, there is a hacky workaround,
Run:
```
mkdir /tmp/libc && \
sudo ln /usr/lib64/libc.so.6 /tmp/libc/libc-2.31.so && \
ln -s libc-2.31.so /tmp/libc/libc.so.6 && \
ln -s libc.so.6 /tmp/libc/libc.so
```
And then run processes you want to inject with `LD_LIBRARY_PATH` set:
```
LD_LIBRARY_PATH=/tmp/libc <cmd_to_debug>
```

**Comment by auxsvr** [comment]
Ran the above with the difference that I used symbolic links everywhere, as /tmp is a different filesystem, to no avail; the error message is the same.

**Comment by kmaork** [comment]
The hard link is required, try running it as I posted just in a different directory in the same filesystem.

**Comment by kmaork** [comment]
Kubo has fixed the issue in injector, I released `pyinjector==1.0.6` with these changes. Please let me know if it works for you :)

**Comment by auxsvr** [comment]
The new version works fine, thank you for the prompt response!

**Comment by kmaork** [comment]
Great to hear, thank you for posting the issue :)
