### ISSUE TITLE
Return DLL Handle

### ISSUE THREAD

**Issue by LabGuy94** [kmaork/pyinjector#19]
Is it possible to get the handle of the injected dll?

**Comment by kmaork** [comment]
I think it should be easy to get. May I ask on what operating system, and for what do you want use use the handle? Maybe it's something that could be added to the API.

**Comment by LabGuy94** [comment]
Windows

**Comment by kmaork** [comment]
Do you need it to unload the library or something else? Because I might add an API for unloading.

**Comment by kmaork** [comment]
@LabGuy94 Try `pyinjector==1.1.1`
