### ISSUE TITLE
Cannot install on win10 via pip

### ISSUE THREAD

**Issue by Scrooge20291224** [kmaork/pyinjector#3]
injector\src\linux\elf.c(27): fatal error C1083: 无法打开包括文件: “elf.h”: No such file or directory

**Comment by kmaork** [comment]
`pyinjector` is not supported on windows yet, although it shouldn't be very hard because `injector`, the wrapped c library, does support windows. You are welcome to add support with a pull request.
Closing in favor of https://github.com/kmaork/pyinjector/issues/4
