### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by kernelcore32** [kmaork/pyinjector#32]
Hey I was wondering how strong this system really is? Can it inject into 64 bit processes for example? How stable is the api? Thank you for your answer and I can completly understand if you don't want to answer. :D

**Comment by kmaork** [comment]
> Can it inject into 64 bit processes for example?

Yes!

> How stable is the api?

Stable :)

If you'd elaborate a bit more about what you are considering using it for, I could help more.
